# SLU10 - Classification: Exercise notebook

In [ ]:
import pandas as pd 
import numpy as np 
from sklearn.linear_model import SGDClassifier

In this notebook you will practice the following: 

    - What classification is for
    - Logistic regression
    - Cost function (concept)
    - Binary classification
    - Multiclass classification
    - Sklearn logit
    
You thought that you would get away without implementing your own little Logistic Regression? Hah!


# Exercise 1. Implement the Logistic Function
*aka the sigmoid function*

As a very simple warmup, you will implement the logistic function. Let's keep this simple!

Here's a quick reminder of the formula:

$$\hat{p} = \frac{1}{1 + e^{-z}}$$

**Complete here:**

In [ ]:
def logistic_function(z):
    """ 
    Implementation of the logistic function by hand
    
    Args:
        z (np.float64): a float

    Returns:
        proba (np.float64): the predicted probability for a given observation

    """
    
    # define the numerator and the denominator and obtain the predicted probability 
    ### START CODE HERE ### (~3 lines)
    numerator = None
    denominator = None
    proba = None
    ### END CODE HERE ###
    return proba

In [ ]:
z = 1.2
print('Predicted probability: %.2f' % logistic_function(z))

Expected output:

    Predicted probability: 0.77

In [ ]:
z = 3.4
assert np.isclose(np.round(logistic_function(z),2), 0.97)


# Exercise 2: Make Predictions From Observations

The next step is to implement a function that receives observations and returns predicted probabilities.

For instance, remember that for an observation with two variables we have:

$$z = \beta_0 + \beta_1 x_1 + \beta_2 x_2$$

where $\beta_0$ is the intercept and $\beta_1, \beta_2$ are the coefficients.

**Complete here:**

In [ ]:
def predict_proba(x, coefficients):
    """ 
    Implementation of a function that returns a predicted probability for a given data observation
    
    Args:
        x (np.array): a numpy array of shape (n,)
            - n: number of variables
        coefficients (np.array): a numpy array of shape (n + 1,)
            - coefficients[0]: intercept
            - coefficients[1:]: remaining coefficients

    Returns:
        proba (np.array): the predicted probability for a given data observation

    """
    
    # start by assigning the intercept to z 
    # clue: the intercept is the first element of the list of coefficients
    ### START CODE HERE ### (~1 line)
    z = None
    ### END CODE HERE ###
    
    # sum the remaining variable * coefficient products to z
    # clue: the variables and coefficients indeces are not exactly aligned, but correctly ordered
    ### START CODE HERE ### (~2 lines)
    for i in range(None):                     # iterate through the observation variables
        z += None                             # multiply the variable value by its coefficient and add to proba
    ### END CODE HERE ###

    # obtain the predicted probability from z
    # clue: we already implemented something that can give us that
    ### START CODE HERE ### (~1 line)
    proba = None
    ### END CODE HERE ###

    return proba

In [ ]:
x = np.array([0.2,2.32,1.3,3.2])
coefficients = np.array([2.1,0.22,-2, 0.4, 0.1])
print('Predicted probability:  %.3f' % predict_proba(x, coefficients))

Expected output:

    Predicted probability:  0.160

In [ ]:
x = np.array([1,0,2,3.2])
coefficients = np.array([-0.2,2,-6, 1.2, -1])
assert np.isclose(np.round(predict_proba(x, coefficients),2), 0.73)


# Exercise 3: Compute the Cross-Entropy Cost Function

As you will implement stochastic gradient descent, you only have to do the following for each prediction: 

$$H_{\hat{p}}(y) =  - (y \log(\hat{p}) + (1-y) \log (1-\hat{p}))$$


In [ ]:
def cross_entropy(y, proba):
    """ 
    Implementation of a function that returns the Cross-Entropy loss
    
    Args:
        y (np.int64): an integer
        proba (np.float64): a float

    Returns:
        loss (np.float): a float with the resulting loss for a given prediction

    """
    
    # compute the inner left side of the loss function (for when y == 1)
    ### START CODE HERE ### (~1 line)
    left = None 
    ### END CODE HERE ###

    # compute the inner right side of the loss function (for when y == 0)
    ### START CODE HERE ### (~1 line)
    right = None 
    ### END CODE HERE ###
   
    # compute the total loss
    # clue: do not forget the minus sign
    ### START CODE HERE ### (~1 line)
    loss = None
    ### END CODE HERE ###
    
    return loss

In [ ]:
y = 1
proba = 0.7
print('Computed loss:  %.3f' % cross_entropy(y, proba))

Expected output:
    
    Computed loss:  0.357

In [ ]:
y = 1
proba = 0.35
assert np.isclose(np.round(cross_entropy(y, proba),3), 1.050)


# Exercise 4: Obtain the Optimized Coefficients 
Now that the warmup is done, let's do the most interesting exercise. Here you will implement the optimized coefficients through Stochastic Gradient Descent.

Quick reminders:

$$H_{\hat{p}}(y) = - \frac{1}{N}\sum_{i=1}^{N} \left [{ y_i \ \log(\hat{p}_i) + (1-y_i) \ \log (1-\hat{p}_i)} \right ]$$

and

$$\beta_{0(t+1)} = \beta_{0(t)} - learning\_rate \frac{\partial H_{\hat{p}}(y)}{\partial \beta_{0(t)}}$$

$$\beta_{t+1} = \beta_t - learning\_rate \frac{\partial H_{\hat{p}}(y)}{\partial \beta_t}$$

which can be simplified to

$$\beta_{0(t+1)} = \beta_{0(t)} + learning\_rate \left [(y - \hat{p}) \ \hat{p} \ (1 - \hat{p})\right]$$

$$\beta_{t+1} = \beta_t + learning\_rate \left [(y - \hat{p}) \ \hat{p} \ (1 - \hat{p}) \ x \right]$$

In [ ]:
def compute_coefficients(x_train, y_train, learning_rate = 0.1, n_epoch = 50, verbose = False):
    """ 
    Implementation of a function that returns the optimized intercept and coefficients
    
    Args:
        x_train (np.array): a numpy array of shape (m, n)
            m: number of training observations
            n: number of variables
        y_train (np.array): a numpy array of shape (m,)
        learning_rate (np.float64): a float
        n_epoch (np.int64): an integer of the number of full training cycles to perform on the training set

    Returns:
        coefficients (np.array): a numpy array of shape (n+1,)

    """
    
    # initialize the coefficients array with zeros
    # clue: use np.zeros()
    ### START CODE HERE ### (~1 line)
    coefficients = None
    ### END CODE HERE ###
    
    # run the stochastic gradient descent algorithm n_epoch times and update the coefficients
    ### START CODE HERE ### (~9 lines)
    for n_epoch in range(None):               # iterate n_epoch times
        loss = None                         # initialize the cross entropy loss
        for x, y in zip(None, None):        # iterate through the training set observations and labels
            proba = None                    # compute the predicted probability
            loss += None                    # compute the cross entropy loss and add it
            coefficients[0] += None         # update the intercept            
            for i in range(None):           # iterate through the observation variables
                coefficients[i + 1] += None # update each coefficient
        loss /= None                        # average the summed cross entropies
    ### END CODE HERE ### 
        if(n_epoch%10):
            print('>epoch=%d, learning_rate=%.3f, error=%.3f' % (n_epoch, learning_rate, loss))
    return coefficients

In [ ]:
x_train = np.array([[1,2,3], [2,5,9], [3,1,4], [8,2,9]])
y_train = np.array([0,1,0,1])
learning_rate = 0.1
n_epoch = 50
coefficients = compute_coefficients(x_train, y_train, learning_rate=learning_rate, n_epoch=n_epoch, verbose=True)
print('Computed coefficients:')
print(coefficients)

Expected output:
    
    epoch=0, learning_rate=0.100, error=0.811
    epoch=10, learning_rate=0.100, error=0.675
    epoch=20, learning_rate=0.100, error=0.640
    epoch=30, learning_rate=0.100, error=0.606
    epoch=40, learning_rate=0.100, error=0.574
    Computed coefficients:
    [-0.82964483  0.02698239 -0.04632395  0.27761155]

In [ ]:
x_train = np.array([[3,1,3], [1,0,9], [3,3,4], [2,-1,10]])
y_train = np.array([0,1,0,1])
learning_rate = 0.3
n_epoch = 100
coefficients = compute_coefficients(x_train, y_train, learning_rate=learning_rate, n_epoch=n_epoch, verbose=False)
assert np.allclose(coefficients, np.array([-0.25917811, -1.15128387, -0.85317139,  0.55286134]))


# Exercise 5: Normalize Data

Just a quick and easy function to normalize the data. It is crucial that your variables are adjusted between $[0;1]$ (normalized) or standardized so that you can correctly analyse some logistic regression coefficients for your possible future employer.

You only have to implement this formula

$$ x_{normalized} = \frac{x - x_{min}}{x_{max} - x_{min}}$$

In [ ]:
def normalize_data(data):
    """ 
    Implementation of a function that normalizes your data variables
    
    Args:
        data (np.array): a numpy array of shape (m, n)
            m: number of observations
            n: number of variables

    Returns:
        normalized_data (np.array): a numpy array of shape (m, n)

    """
    # compute the numerator
    # clue: use np.min()
    ### START CODE HERE ### (~1 line)
    numerator = None
    ### END CODE HERE ###
    
    # compute the numerator
    # clue: use np.max() and np.min()
    ### START CODE HERE ### (~1 line)
    denominator = None
    ### END CODE HERE ###
    
    # obtain the normalized data
    ### START CODE HERE ### (~1 line)
    normalized_data = None
    ### END CODE HERE ###
    
    return normalized_data

In [ ]:
data = np.array([[9,5,2], [7,7,3], [2,2,11], [1,5,2], [10,1,3], [0,9,5]])
normalized_data = normalize_data(data)
print('Before normalization:')
print(data)
print('\n-------------------\n')
print('After normalization:')
print(normalized_data)

Expected output:
    
    Before normalization:
    [[ 9  5  2]
     [ 7  7  3]
     [ 2  2 11]
     [ 1  5  2]
     [10  1  3]
     [ 0  9  5]]

    -------------------

    After normalization:
    [[0.9        0.5        0.        ]
     [0.7        0.75       0.11111111]
     [0.2        0.125      1.        ]
     [0.1        0.5        0.        ]
     [1.         0.         0.11111111]
     [0.         1.         0.33333333]]

In [ ]:
data = np.array([[9,5,2,6], [7,5,1,3], [2,2,11,1]])
normalized_data = normalize_data(data)
assert np.allclose(normalized_data, np.array([[1., 1., 0.1, 1.],[0.71428571, 1., 0., 0.4],[0., 0., 1., 0.]]))


# Exercise 6: Putting it All Together



The Wisconsin Breast Cancer Diagnostic dataset is another data science classic. It is the result of extraction of breast cell's nuclei characteristics to understand which of them are the most relevent for developing breast cancer.

Your quest, is to first analyze this dataset from the materials that you've learned in the previous SLUs and then create a logistic regression model that can correctly classify cancer cells from healthy ones.

Dataset description:

    1. Sample code number: id number 
    2. Clump Thickness
    3. Uniformity of Cell Size
    4. Uniformity of Cell Shape
    5. Marginal Adhesion 
    6. Single Epithelial Cell Size
    7. Bare Nuclei
    8. Bland Chromatin
    9. Normal Nucleoli
    10. Mitoses 
    11. Class: (2 for benign, 4 for malignant) > We will modify to (0 for benign, 1 for malignant) for simplicity
    
The data is loaded for you below.

In [ ]:
columns = ['Sample code number','Clump Thickness','Uniformity of Cell Size','Uniformity of Cell Shape',
           'Marginal Adhesion','Single Epithelial Cell Size','Bare Nuclei','Bland Chromatin','Normal Nucleoli',
           'Mitoses','Class']
data = pd.read_csv('data/breast-cancer-wisconsin.csv',names=columns, index_col=0)
data["Bare Nuclei"] = data["Bare Nuclei"].replace(['?'],np.nan)
data = data.dropna()
data["Bare Nuclei"] = data["Bare Nuclei"].map(int)
data.Class = data.Class.map(lambda x: 1 if x == 4 else 0)
X = data.drop('Class').values
y_train = data.Class.values

And use these values for your logistic regression.

In [ ]:
# Hyperparameters
learning_rate = 0.01
n_epoch = 100

# For validation
verbose = True

Now let's do this!

In [ ]:
# Explore the dataset

# How many patients have breast cancer?
### START CODE HERE ### (~1 line)
n_cancer = None
### END CODE HERE ### 

# How many patients are healthy?
### START CODE HERE ### (~1 line)
n_healthy = None
### END CODE HERE ### 

# Normalize the training data X
### START CODE HERE ### (~1 line)
x_train = None
### END CODE HERE ### 

# What coefficients can we get?
### START CODE HERE ### (~1 line)
coefficients = None
### END CODE HERE ### 

# Initialize the predicted probabilities list
### START CODE HERE ### (~1 line)
probas = None
### END CODE HERE ### 

# What are the predicted probabilities on the training data?
### START CODE HERE ### (~2 lines)
for x in None:
    probas.append(None)
### END CODE HERE ### 

# If we had to say whether a patient had breast cancer, what are the predictions?
# clue 1: Hard assign the predicted probabilities by rounding them to the nearest integer
# clue 2: use np.round()
### START CODE HERE ### (~1 line)
preds = None
### END CODE HERE ### 

# How many patients were predicted to have breast cancer?
### START CODE HERE ### (~1 line)
n_predicted_cancer = None
### END CODE HERE ### 

# How many patients with cancer were correctly detected?
### START CODE HERE ### (~1 line)
n_correct_cancer_predictions = None
### END CODE HERE ### 

In [ ]:
print('You have a dataset with %s cells with cancer and %s healthy cells. \n\n'
     'After analysing the data and training your own logistic regression classifier you find out that it correctly '
     'identified %s out of %s cancer cells which were all of them. You feel very lucky and happy. However, shortly '
     'after you get somewhat suspicious after getting such amazing results. You feel that they should not be '
     'that good, but you do not know how to be sure of it. You say to yourself that you will definitely be '
     'present when doing the next Small Learning Unit 11, which will tackle exactly that.' % 
      (n_cancer, n_healthy, n_predicted_cancer, n_correct_cancer_predictions))

**Test output (don't change code here)**

# Exercise 7: Using the Sklearn's SGDClassifier

As a final exercise, you will do exactly what you did in the previous one, but now by using the sklearn's Logistic Regression implementation.

Let's just define the hyperparameters first, be sure to use them!

In [ ]:
# Hyperparameters
learning_rate = 0.01
learning_rate_schedule = "constant"
n_epoch = 100
loss = "log"
random_state = 0
penalty = None
shuffle = False

Now let's do this!

In [ ]:
# Create the sklearn's SGDClassifier object with the training data
### START CODE HERE ### (~1 line)
clf = None
### END CODE HERE ### 

# Fit the classifier with the training data
### START CODE HERE ### (~1 line)

### END CODE HERE ### 
 
# What coefficients can we get?
### START CODE HERE ### (~1 line)
coefficients = None
### END CODE HERE ### 

# What are the predicted probabilities on the training data?
### START CODE HERE ### (~1 line)
probas = None
### END CODE HERE ### 

# If we had to say whether a patient had breast cancer, what are the predictions?
# Suggestion: This time, try to do the same but with a logistic regression method
### START CODE HERE ### (~1 line)
preds = None
### END CODE HERE ### 

# How many patients were predicted to have breast cancer?
### START CODE HERE ### (~1 line)
n_predicted_cancer = None
### END CODE HERE ### 

# How many patients with cancer were correctly detected?
### START CODE HERE ### (~1 line)
n_correct_cancer_predictions = None
### END CODE HERE ### 

In [ ]:
print('You have a dataset with %s cells with cancer and %s healthy cells. \n\n'
     'After analysing the data and training the sklearn\'s SGDClassifier you find out that it correctly '
     'identified %s out of %s cancer cells which were all of them. You feel very lucky and happy. However, shortly '
     'after you get somewhat suspicious after getting such amazing results. You feel that they should not be '
     'that good, but you do not know how to be sure of it. You say to yourself that you will definitely be '
     'present when doing the next Small Learning Unit 11, which will tackle exactly that.' % 
      (n_cancer, n_healthy, n_predicted_cancer, n_correct_cancer_predictions))

**Test output (don't change code here)**