# SLU18 - Unsupervised Learning: Exercise notebook

In [ ]:
import pandas as pd 
import numpy as np 

In this notebook you will practice the following: 

    - Clustering
    - K-means
    
You thought that you would get away without implementing your own little K-means algorithm?


# Exercise 1. Implement the Manhattan Distance Function

Only because the euclidean distance is too mainstream. And trust me on this one.

Here's a quick reminder of the formula:

$$d_{manhattan}(X,Y) = \left \| \ \mathbf{X} - \mathbf{Y} \ \right \|_1 = \left | \ x_1-y_1 \ \right | + \left | \ x_2-y_2 \ \right | + \ ...$$

If you have problems completing this, consider that you want to subtract the feature values of index $i$ between an `origin` and a `point`. You would do it this way:

```python
result = origin[i] - point[i]
```

**Complete here:**

In [ ]:
def manhattan_distance(origin, point):
    """ 
    Implementation of the manhattan distance by hand
    
    Args:
        origin (np.array): a numpy array containing the coordinates of an observation. Has shape (n,) where:
            - n: The number of features
        point (np.array): a numpy array containing the coordinates of another observation. Has shape (,n) where:
            - n: The number of features

    Returns:
        distance (np.float64): the  for a given observation pair

    """
    
    # initialize the distance with a zero
    distance = None
    # YOUR CODE HERE
    raise NotImplementedError()
    
    # compute the manhattan distance between origin and point
    # clue: use np.abs() to obtain the absolute value
    for i in range(None):            # iterate through each feature column index i (clue: use len() or .shape[0])
        distance += None             # add the absolute value of the difference between the points' feature values 
    # YOUR CODE HERE
    raise NotImplementedError()
    
    return distance

In [ ]:
a = np.array([1,1,0,0,1])
b = np.array([0,1,1,0,1])
print('Manhattan Distance: %.2f' % manhattan_distance(a, b))

Expected output:

    Manhattan Distance: 2.00

In [ ]:
a = np.array([1,0,1,1,1,1,0])
b = np.array([1,0,1,0,1,0,1])
assert np.isclose(manhattan_distance(a, b), 3)


# Exercise 2: Initialize Centroids

The next step is to implement a function that initializes a set of k centroids.

The main idea is that we will shuffle the data that we receive and then grab the first $k$ observations of the shuffled data. To shuffle a numpy array `data`, we would only have to do the following:

```python
np.random.shuffle(data)
```

`np.random.shuffle` already shuffles the data inplace, so we only have to do that.

**Complete here:**

In [ ]:
def initialize_centroids(data, k, seed = None):
    """ 
    Implementation of a function that initializes a set of k centroid coordinates from existing data points
    
    Args:
        data (np.array): a numpy array of shape (m,n)
            - m: number of observations
            - n: number of variables
        k (np.int64): the number of centroids to initialize
        seed (np.int64): the random seed for result reproducibility

    Returns:
        C (np.array): the initialized centroid centers of shape (k, n)

    """
    # this step is just to make the results reproducible
    if seed is not None:    
        np.random.seed(seed)
        
    # copy the data in order not to modify the original one
    # clue: use np.copy() 
    new_data = None
    # YOUR CODE HERE
    raise NotImplementedError()
    
    # shuffle new_data
    # clue: use np.random.shuffle()
    # note: np.random.shuffle() modifies the data inplace!
    # YOUR CODE HERE
    raise NotImplementedError()
    
    # get the first k observations from shuffle new_data
    C = None
    # YOUR CODE HERE
    raise NotImplementedError()

    return C

In [ ]:
x = np.array([[0,1,0], [1,0,0], [0,0,0], [1,1,1], [1,0,1]])
k = 2
print("Obtained centroids:")
print(initialize_centroids(x, k, seed=0))

Expected output:

    Obtained centroids:
    [[0 0 0]
     [0 1 0]]

In [ ]:
x = np.array([[0,1,0,1], [1,0,0,0], [0,0,0,1], [0,1,1,0], [1,1,1,0]])
k = 2
assert np.allclose(initialize_centroids(x, k, seed=10),np.array([[0,0,0,1],[0,1,1,0]]))


# Exercise 3: Implement the Data Assignment Step

In this step, each data point is assigned to its nearest centroid, based on the manhattan distance. More formally, if $c_i$ is the collection of centroids in set $C$, then each data point $x$ is assigned to a cluster based on

$$\underset{c_i \in C}{\arg\min} \; d_{manhattan}(c_i,x)$$

**Complete here:**

In [ ]:
def assign_data(data, C, labels):
    """ 
    Implementation of the data assignment step of the K-means algorithm
    
    Args:
        data (np.array): a numpy array containing the data of shape (m,n)
            - m: number of observations
            - n: number of variables
        C (np.array): a numpy array containing the centroid coordinates of shape (k,n)
            - k: number of centroids
            - n: number of variables
        labels (np.array): a numpy array containing the cluster labels assigned to each observation
    Returns:
        labels (np.array): the updated cluster labels assigned to each observation

    """
    
    # implement the first step of the k-means algorithm
    for i in range(None):                # iterate through each data observation index i (clue: use len() or .shape[0])
        cluster_index = None             # initialize the first cluster index with a zero
        min_dist = None                  # initialize the minimum observation distance with a np.inf
        for centroid in None:            # iterate through each centroid array C
            distance = None              # compute the manhattan distance between the observation i and centroid
            if distance < None:          # see if the new distance is smaller than minimum observation distance
                min_dist = None          # update the minimum observation distance with the new distance
                labels[i] = None         # update the cluster label of observation i with the current cluster index
            cluster_index += None        # increment the cluster index
    
    # YOUR CODE HERE
    raise NotImplementedError()
    return labels

In [ ]:
x = np.array([[0,1,1], [0,0,0], [0,1,0], [1,1,1]])
C = np.array([[0,0,0], [1,1,1]])
labels = np.array([0,0,0,0])
print("The following labels were assigned:")
print(assign_data(x, C, labels))

Expected output:
    
    The following labels were assigned:
    [1 0 0 1]

In [ ]:
x = np.array([[0,1,1,1], [0,0,1,0], [1,0,1,0], [0,1,1,1]])
C = np.array([[0,0,0,1], [1,1,1,0], [0,1,1,0]])
labels = np.array([0,0,0,0])
assert np.allclose(assign_data(x, C, labels), np.array([2, 2, 1, 2]))


# Exercise 4: Implement the Centroid Update Step

In this step, the centroids are recomputed. This is done by taking the mean of all data points assigned to that centroid's cluster. With the set of data observation assignments for each ith cluster centroid being $S_i$, remember that:

$$c_i=\frac{1}{|S_i|}\sum_{x_i \in S_i}x_i$$

Remember that when we want to filter a numpy array `data` that matches a specific `label` value, such as $3$, we do the following:


```python
filtered_data = data[label==3]
```

Additionally, remember that when obtaining the new centroid coordinates, every feature will be the mean of that specific feature over all observations assigned to the cluster. Thus, we would obtain the new coordinates this way:

```python
centroid = np.mean(data,axis=0)
```

We use `axis=0`, because we want the mean of each individual feature.

**Complete here:**

In [ ]:
def update_centroids(data, C, labels):
    """ 
    Implementation of the data assignment step of the K-means algorithm
    
    Args:
        data (np.array): a numpy array containing the data of shape (m,n)
            - m: number of observations
            - n: number of variables
        C (np.array): a numpy array containing the centroid coordinates of shape (k,n)
            - k: number of centroids
            - n: number of variables
        labels (np.array): a numpy array containing the cluster labels assigned to each observation
    Returns:
        C (np.array): the updated centroid coordinates

    """
    # implement the second step of the k-means algorithm
    for i in range(None):            # iterate through each centroid index i
        assigned_data = None         # use a mask to filter the data observations that have label i
        C[i] = None                  # compute the mean of the assigned data's features (clue: use np.mean())
    # YOUR CODE HERE
    raise NotImplementedError()
    return C

In [ ]:
x = np.array([[0,1,1], [0,0,0], [0,1,0], [1,1,1]])
C = np.array([[0,0,0], [1,1,1]])
labels = np.array([1,1,1,0])
print("The following labels were assigned:")
print(update_centroids(x, C, labels))

Expected output:
    
    The following labels were assigned:
    [[1 1 1]
     [0 0 0]]

In [ ]:
x = np.array([[0,1,1,0], [1,0,0,0], [1,0,1,0], [0,1,1,1], [1,0,0,1]])
C = np.array([[0,0,1,0], [1,1,0,1]])
labels = np.array([0,0,1,0,0])
assert np.allclose(update_centroids(x,C,labels), np.array([[0,0,0,0],[1,0,1,0]]))


# Exercise 5: Implementing K-Means

Now that you've implemented all of the main K-means functions, you can now easily implement your own K-Means! 

Remember that when initializing a numpy array of zeros we need to specify its shape inside a tuple. For instance, if we wanted a numpy array of zeros with the same shape as `data`, we would do the following:

```python
zeros = np.zeros((data.shape[0], data.shape[1]))
```

where `data.shape[0]` is the number of observations and `data.shape[1]` is the number of features. Notice the inner parenthesis!

Let's finish this.

**Complete here:**

In [ ]:
def KMeans(data, k=3, n_iter=10, seed=0):
    """ 
    Implementation of the K-Means algorithm
    
    Args:
        data (np.array): a numpy array containing the data of shape (m,n)
            - m: number of observations
            - n: number of variables
        k (np.int64): the number of centroids to use
        n_iter (np.int64): the number of iterations to perform K-Means
        seed (np.int64): the random seed for result reproducibility

    Returns:
        labels (np.array): the cluster label of each observation

    """    
    # initialize the centroids and labels
    # clue: initialize the labels with np.zeros()
    C = None                 # initialize the centroids for the given k and seed (clue: we already implemented this)
    labels = None            # initialize the labels with zeros and shape (m,) m: number of observations of data
    # YOUR CODE HERE
    raise NotImplementedError()
    
    # the main K-Means loop
    for i in range(None):    # iterate n_iter times   
        labels = None        # Assign each observation to its closest cluster (step one, we implemented this)
        C = None             # Find the new centroids (step two, we also implemented this)
    # YOUR CODE HERE
    raise NotImplementedError()
    
    return labels

In [ ]:
x = np.array([[0,1,1,0], [0,0,1,0], [0,1,0,0], [0,1,1,1], [1,1,1,1]])
print("The clustered labels are the following:")
print(KMeans(x, k=3, seed=3))

Expected output:
    
    The clustered labels are the following:
    [ 0.  2.  0.  1.  1.]

In [ ]:
x = np.array([[0,1,1,1], [1,0,1,0], [0,0,0,0], [0,1,1,1], [1,0,1,1]])
assert np.allclose(KMeans(x, k=2, seed=10), np.array([ 1.,  0.,  0.,  1.,  1.]))


# Exercise 6: Exploring with K-Means

First, a bit of context regarding the data we will use. 

>_Bob Ross was a consummate teacher. He guided fans along as he painted “happy trees,” “almighty mountains” and “fluffy clouds” over the course of his 11-year television career on his PBS show, “The Joy of Painting.” In total, Ross painted 381 works on the show, relying on a distinct set of elements, scenes and themes, and thereby providing thousands of data points._

The dataset that we will use was gathered for this story https://fivethirtyeight.com/features/a-statistical-analysis-of-the-work-of-bob-ross/

The data consists of 403 paintings with 67 binary features telling whether or not a particular element was present in each painting. As all features are binary, that was why we implemented the manhattan distance function. The manhattan distance is is equivalent to the [Hamming Distance](https://en.wikipedia.org/wiki/Hamming_distance) when we only have binary features, which is the most suited distance metric for this dataset.

Your task in this exercise is to run your freshly made K-Means algorithm and try to find some interesting findings about his painting style.

Let me prepare the data for you!

In [ ]:
bob_ross = pd.read_csv("data/elements-by-episode.csv").drop("EPISODE",axis=1)
TITLES = bob_ross.TITLE.copy()
bob_ross = bob_ross.drop("TITLE",axis=1)
data = bob_ross.values
bob_ross.head()

Again, remember that when we want to filter a numpy array called `happy_trees` that matches a specific `label` value, such as $3$, we do the following:

```python
really_happy_trees = happy_trees[label==3]
```

In this exercise you will be asked to sum the values of each column and sort them in descending order. To do so, imagine that you have a dataframe called fluffy_clouds. Let's to this with two steps. To sum the values of each column we would do the following:

```python
flattened_clouds = fluffy_clouds.sum()
```
This would return a `pd.Series` object with the summed feature values. Now, if wanted to sort those values in descending order, we would then do the following:

```python
staired_clouds = flattened_clouds.sort_values(ascending=False)
```
Or we could simply do all of this at once:

```python
staired_clouds = fluffy_clouds.sum().sort_values(ascending=False)
```

Finally, if we then wanted to know the two features with the highest values, we only had to do the following:

```python
top2_clouds = staired_clouds.index[:2]
```
As the features are in the index (because it is now a `pd.Series`), and the values are already sorted. 

Let's just define the number of clusters k and our random seed before continuing.

In [ ]:
k = 3
n_iter = 3
seed = 0

This is the last one. Go and get it!

**Complete here:**

In [ ]:
# apply kmeans with the hyperparameters above and return the clustered labels
labels = None
# YOUR CODE HERE
raise NotImplementedError()

# for each label (0 to 2), obtain the filtered bob_ross dataframe with the corresponding labels
label_0 = None
label_1 = None
label_2 = None
# YOUR CODE HERE
raise NotImplementedError()

# for each created label_0 to 2 dataframes, sum the values of each column and sort them in descending order
# clue: use .sum() and .sort_values()
label_0_counts = None
label_1_counts = None
label_2_counts = None
# YOUR CODE HERE
raise NotImplementedError()

# for each created label_0-2_counts dataframes, obtain the three most common features (clue: use .index)
label_0_common_features = None
label_1_common_features = None
label_2_common_features = None
# YOUR CODE HERE
raise NotImplementedError()


In [ ]:
print('After applying your freshly make KMeans algorithm with k=3, you start analysing your clusters. '
      'You see that your first, second and third clusters had %s, %s and %s rows, respectively. '
      'You then decide to go through each one. \n\nYou see that your first cluster had the highest value count '
      'of %s and that the three most common painting features were %s, %s and %s, thus more florest themed.\n\n'
      'Then you visit the second cluster and see that the highest value count was %s and that the three most '
      'common painting features were %s, %s and %s, thus more pure and white themed.\n\nFinally, you visit the '
      'last cluster and see something strange. You see that the highest value count was %s! You then go take a '
      'look at the dataset and confirm that those three clustered rows were completely empty and your K-Means '
      'simply clustered them together.'
      % (label_0.shape[0], label_1.shape[0], label_2.shape[0], label_0_counts[0], label_0_common_features[0],
        label_0_common_features[1],label_0_common_features[2], label_1_counts[0], label_1_common_features[0],
        label_1_common_features[1],label_1_common_features[2], label_2_counts[0]))

**Test output (don't change code here)**